# Rules Configuration
rules:

  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-hex: 2
  no-color-keywords: 2
  no-color-literals: 2
  no-debug: 1
  no-ids: 0
  no-important: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-invalid-hex: 2
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-vendor-prefixes: 0
  no-warn: 1

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format: 0
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format:
    - 2
    -
      convention: camelcase

  # Style Guide
  bem-depth:
    - 1
    -
      max-depth: 3
  border-zero:
    - 2
    -
      convention: 'none'
  clean-import-paths: 0
  empty-args: 2
  hex-length:
    - 1
    -
      style: long
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  leading-zero:
    - 1
    -
      include: true
  nesting-depth:
    - 1
    -
      max-depth: 5
  property-sort-order:
    - 2
    -
      order: 'smacss'
  variable-for-property:
    - 2
    -
      'properties':
      - 'color'
      - 'background-color'
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
